name: Build & Test

on:
    pull_request:
        branches: [master]

concurrency:
    # Allow this workflow to run concurrently on multiple branches, but cancel
    # other jobs for the same branch:
    group: ci-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps

            - name: ESLint
              run: pnpm lint

            - name: Unit test
              run: pnpm run test:coverage

            - name: Run Playwright tests
              run: pnpm exec playwright test
