name: Build & Test

on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

if: false # disable for now

concurrency:
    # Allow this workflow to run concurrently on multiple branches, but cancel
    # other jobs for the same branch:
    group: ci-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

    lint:
        runs-on: ubuntu-latest
        needs: [setup]
        steps:
            - name: ESLint
              run: pnpm lint
